version: 2.1

orbs:
  python: circleci/python@1.0.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
      - run:
          command: poetry install --no-dev
          name: Install dependencies
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          command: poetry run flake8
          name: Lint
      - run:
          command: poetry run coverage run -m runner
          name: Test
      - run:
          command: poetry run coverage report
          name: Report

workflows:
  main:
    jobs:
      - build-and-test
